project_id = "lqbpqecybxdylqjedwza"

[functions.enhance-video-prompt]
verify_jwt = false

[functions.generate-ai-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false
