// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqbpqecybxdylqjedwza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYnBxZWN5YnhkeWxxamVkd3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTk1NjMsImV4cCI6MjA2ODYzNTU2M30.-NN_DGqKaNghcnrzYW075KTg_f4W6i-z3n6y4Tq1L_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});